client_id :  'xxxxxxx'
client_secret : 'xxxxxxxxxxx'
refresh_token : 'None'
protocol : 'https'
domain : 'io.catchpoint.com/ui/api'
token_endpoint: 'token'
version : 'v1'
rawdata_endpoint : 'performance/raw?tests'
test_ids: { 
        web: ['142637'], 
        transaction: [],
        api: [],
        ping: [],
        traceroute: [],
        dns: [],
        websocket: [],
        smtp: [],
        transport: [],
        ftp: [],
        custom: [],
        ntp: [],
        imap: [],
        ssl: [],
        html: [],
        streaming: []
              
          }
# get_logger  
batch_size : 10
log_file : 'app.log'
log_level : 'debug'
